import type { Metadata } from 'next';
import { Work_Sans, Arimo } from 'next/font/google';
import './globals.css';

const workSans = Work_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
});

const arimoMono = Arimo({
  variable: '--font-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-primary ${workSans.variable} ${arimoMono.variable} antialiased pt-28 pb-6 lg:pt-40 lg:pb-8`}
      >
        {children}
      </body>
    </html>
  );
}
